version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: booking_postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: tst
      POSTGRES_PASSWORD: tst
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tst -d booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: booking_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  redis_data:
