###
# @name get availiable
GET http://localhost:8080/api/v1/cache

###
# @name create unit
###
POST http://localhost:8080/api/v1/units
Content-Type: application/json

{
  "roomsNumber": 1,
  "accommodationType": "HOME",
  "floor": 1,
  "baseCost": 100,
  "description": "description of unit"
}

###
# @name search unit
###
POST http://localhost:8080/api/v1/units/search
Content-Type: application/json

{
  "roomsNumber": 2
}

###
# @name create booking
###
POST http://localhost:8080/api/v1/bookings
Content-Type: application/json

{
  "unitId": 11,
  "userId": 2,
  "startDate": "2025-03-26T00:00",
  "endDate": "2025-03-27T00:00"
}
